### ISSUE TITLE
The difference between persisting and saving data to db by using ORMs  

### ISSUE THREAD

**Issue by lednhatkhanh** [ncthbrt/nact#32]
It would be great if you can tell a little bit more about persisting in the docs, when should we use it and what is the difference between persisting and saving data to db by using ORMs . Thank you.

**Comment by ncthbrt** [comment]
@lednhatkhanh I could expand on event sourcing in the docs a little more, but a quick answer is that ORMs are designed to allow you to more easily (and safely) interact with a given database from a host language.

While nact also provides an abstraction layer around databases, this has a more opinionated goal, which is to make it easier to design an event sourced architecture and hence forgoes a lot of the features that most ORMs would provide.

Here are a few great links which might help you understand the problem Nact is trying to solve. The youtube link is one I'd highly recommend:

https://www.youtube.com/watch?v=STKCRSUsyP0
https://martinfowler.com/eaaDev/EventSourcing.html

**Comment by ncthbrt** [comment]
I'm going to close this issue if you don't mind; I'll make a note about expanding the persistence docs,  but happy to chat about it on  (discord)[https://discordapp.com/invite/QV78HB]
