### ISSUE TITLE
Remove rxjs dependency 

### ISSUE THREAD

**Issue by ncthbrt** [ncthbrt/nact#43]
Rxjs is quite a heavy dependency and nact doesn't really need it. It is only being used in the persistence layer. The streaming API is most likely only an advantage in pathological cases where hundreds of large events have been persisted.

**Comment by Baransu** [comment]
It would be great to have some benchmarking with and without `rxjs`. In large event sourced systems it's possible to have lot of persistance going on I think. I'm not an expert on event sourcing or `rxjs` just trying to provide some feedback :)

**Comment by ncthbrt** [comment]
Thanks @Baransu. While there maybe be a lot of events, the specific manner in which rxjs is being used leads me to believe that it is unlikely to provide much in the way of performance gains. Additionally, the persistence layer would still be able to support a streaming API.
