### ISSUE TITLE
Snapshotting has one-state lag, leading to "Failed to take snapshot Error: data should not be null or undefined"

### ISSUE THREAD

**Issue by ellis** [ncthbrt/nact#47]
## Expected Behavior

The snapshot is taken on the state after the first message, rather than on the null state.

## Current Behavior

With `snapshotEvery: 1 * messages`, I noticed that the snapshot is always one state behind.

This also leads to the error `"Failed to take snapshot Error: data should not be null or undefined"` when nact tries to persists the first time.

## Steps to Reproduce (for bugs)

1. Spawn a persistant actor with the option `{snapshotEvery: 1 * messages}`
2. Process a message to create the state object

## Context

It'd be nice if the snapshot took place after the message is processed rather than before (if that's indeed what's happening).  This would ensure that the snapshot is really up-to-date and avoid re-processing the last message every time the actor is restarted.

## Your Environment

* Version used: 6.1.0 (and nact-persistence-postgres v6.0.2)
* Environment name and version (e.g. Node v8.8): node 9.6
* Operating System and version: OS X 10.10.5

**Comment by ncthbrt** [comment]
Thanks @ellis. I'll investigate and get back to you. 
:) 
Thanks so much for the great bug report.

**Comment by ncthbrt** [comment]
If this is indeed the case, may also take the opportunity to introduce snapshot hooks allowing one to better control the representation of the snapshot.

**Comment by ellis** [comment]
@ncthbrt Interesting clarifications.  I'm not sure whether I completely understand, though.  What I observed was this: there was always one fewer rows in `snapshot_store` than in `event_journal`, and the last snapshot corresponded to the second-to-last event.  From you explanation, it doesn't sound like that's the expected behaviour?

**Comment by ncthbrt** [comment]
The pseudocode for persist call is currently as follows:
```javascript
persist() { 
  --messagesToNextSnapshot; 
  if(messagesToNextSnapshot<= 0) { takeSnapshot(state) // Async call. Success/Failure is ignored  } 
   return persistToDb(msg);
}
```
This means that snapshotting is started before the persist of the event. 

I am going to move to change it to:

```javascript
persist() { 
  --messagesToNextSnapshot; 
   return persistToDb(msg);
}
```
And then only take snapshot *after* current message has been processed.

**Comment by ncthbrt** [comment]
Hope that clarifies a little @ellis

**Comment by ellis** [comment]
Great, makes sense, @ncthbrt !

**Comment by ncthbrt** [comment]
Will as always let you know once I've fixed issue @ellis

**Comment by ncthbrt** [comment]
Hi @ellis 
This issue is now resolved in the v7 release!
I made a breaking change (hence the version bump) but I think most users will not be affected as it was not a documented feature and a legacy of this library's Erlang inspiration. .

**Comment by ellis** [comment]
Works perfectly! :)
