### ISSUE TITLE
Could it be that `spawnPersistent` never returns if passed the same name twice?

### ISSUE THREAD

**Issue by ellis** [ncthbrt/nact#49]
## Expected Behavior

I guess I'd expect spawnPersistent to either throw an error or return the existing child with the same name, rather than just not return.

## Current Behavior

I was having a problem with not being able to query an actor twice: the first query succeeded, but then further queries timed out. I ended up tracking the problem down to `spawnPersistent` not returning when the same name was passed to it a second time. 

## Steps to Reproduce (for bugs)

1. Setup the system and actors like in https://nact.io/lesson/javascript/hierarchy
2. Mistakenly pass a fixed name to the spawn function, e.g. instead of  `childActor = spawnUserContactService(ctx.self, userId)` do something like `childActor = spawnUserContactService(ctx.self, "userId")`

The Hierarchy documentation uses `spawn`, but I used `spawnPersistent` - I'm guess that's probably not important in this context.

## Your Environment

* Version used: 7.0.1 (and nact-persistence-postgres v7.0.0)
* Environment name and version: node 9.6
* Operating System and version: OS X 10.10.5

**Comment by ncthbrt** [comment]
It may make a difference whether it is persistent vs non-persistent actors. 

It does check whether a child already exists with the same name:  https://github.com/ncthbrt/nact/blob/master/lib/actor.js#L17

Perhaps there is a bug somewhere which is preventing the collision from registering.  Do you perhaps a repo I can check out to see if I can reproduce the issue?

**Comment by ellis** [comment]
@ncthbrt That's peculiar - it does look like an error should throw.  I wonder whether the exception is getting swallowed somewhere.  I'm afraid my nact-related code is a small part of a much larger private repository, but I can try to create a minimal example sometime later in the week if that'll help.

**Comment by ncthbrt** [comment]
Thanks @ellis 
That'd help a lot.
