### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by nevi-me** [ncthbrt/nact#5]
Hey Nick, project looks interesting! I wanted to ask what are good use cases for nact. I see that you're working on a postgres persistence plugin, I could work on a MongoDB one. I've got some time in my hands and am looking for interesting stuff to do.

**Comment by ncthbrt** [comment]
I remember you mentioning Akka at one point. NAct is trying to solve the same problems but in a more idiomatic way in Node.js.  That'd be really cool. Just need to first get the Postgres one working properly and update the docs to reflect the refactoring I've done. I'm hoping the next version will be look familiar to Redux users.
