### ISSUE TITLE
stateful actor not stopped if null or undefined returned

### ISSUE THREAD

**Issue by krizka** [ncthbrt/nact#51]
stateful actor not stopped if null or undefined returned
as https://nact.io/lesson/javascript/stateful-actors mentioned it should shutdown if returned null or undefined, but child continued to receive messages, passed by parent to child.

## Expected Behavior
actor stopped as child

## Current Behavior
actor still alive

## Possible Solution
check actor state no null or undefined and stop it

## Steps to Reproduce (for bugs)
```
const s = start();
const actor = spawn(s, (state, msg) => { console.log('received', msg); return null; }, 'actor');
dispatch(actor, 'have to exit after this');
dispatch(actor, 'no, still acting');
```

## Context
I want to stop my actors somehow

## Your Environment
* Version used: latest
* Environment name and version (e.g. Node v8.8): Node 9
* Operating System and version: Mac OS

**Comment by ncthbrt** [comment]
Hi @krizka, I deliberately made this change as I felt that stopping actors automatically after returning `null`/`undefined` was non-obvious and dangerous for the general case, and was a legacy of trying to emulate some of Erlang's design principles. 

I must have missed updating this in the docs. Apologies.

If you want to stop your actor, you can import and call `stop(actorRef)`
