### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by civilizeddev** [ncthbrt/nact#54]
## Expected Behavior

Type definitions for TypeScript (index.d.ts) should be provided.

## Current Behavior

There is no type definition provided, either in `nact` or [`@types/nact`](https://github.com/DefinitelyTyped/DefinitelyTyped).

## Possible Solution

https://github.com/civilizeddev/nact/blob/master/lib/index.d.ts
I wrote this above, using it in my own project. I just want to share it.

if you contributors are pleased I think it would be better to rewrite the whole project in TypeScript.

## Context

I am also Java and Scala developer, but currently working with TypeScript in Node. I was pleased that there is akka-like actor implementation even in JavaScript. Thank you.

## Your Environment

* nact 7.2.1
* Node 8.15.0 LTS
* TypeScript 3.3.3

**Comment by ncthbrt** [comment]
Hi @civilizeddev. People have asked me about typescript support before. I haven't really engaged with that language much, but reading your type definition I noticed that you haven't typed the actor refs. 

[Reason Nact](https://github.com/ncthbrt/reason-nact) is a typed wrapper around nact for ReasonML. You'll note that the actor refs constrain the types the messages you can send to an actor. This has the downside that sender can no longer be used (I consider the use of sender to be an antipattern anyway), and the parent actor can't message the children using just the context (actual references would have to be stored in the state) but the big upside is greatly improved type safety. If a roughly analogous API were able to be expressed in typescript I'd be happy to include typings in this project. 

As for a rewrite in typescript itself, I'm afraid that I'd be personally reluctant to take on that work, largely because I haven't used typescript

**Comment by civilizeddev** [comment]
@ncthbrt 

I understand. You want the type definition to have the same type signature as in ReasonML, right?
That's okay. Then I'll take a look at the Reason Nact later.

As for TypeScript, I have this opinion:
- Even if you write the project in TypeScript, eventually it will be provided as plain JavaScript(ES5) as before.
- Type definition(`index.d.ts`) will be automatically generated during the translation (No effort to write the type definitions separately)
- End users can keep using Nact for JavaScript.
- TypeScript users can have required type definitions.
- The contributors can have maintainability, thanks to type safety.
- TypeScript is slightly augmented JavaScript. It is interoperable with JavaScript so that you can even change the `js` files to `ts` one by one when you have time.

Thanks.

**Comment by ncthbrt** [comment]
@civilizeddev I've been thinking about this a little. I'd be happy to merge a typescript PR if it had some tests to go along with it; otherwise the bindings may get out of date.

**Comment by civilizeddev** [comment]
I really appreciate your works, which introduced Akka into Node world.

Now as one of type enthusiasts, I beg you to rewrite nact in TypeScript.

While JavaScript is easy to use (at the very beginning) and has advantage in flexibility (but it can be also disadvantage in different view), I think it has clear limit in terms of scalability and maintainability.

For example, during reviewing the nact source code to annotate the types on, I got troubled in reasoning about, inferencing and restructuring types of parameters and variables in my brain.

Some parts of code uses kind of duck typings, which violates the rule in terms of type safety.

> e.g. Given an **ActorSystem**, but it contains only `name` in it

My opinion is this:

> It's much better to embed type definition in the source code instead of storing in your brain.

To be more robust and maintainable project, I hope you would rewrite it in TypeScript.

**Comment by civilizeddev** [comment]
# Announcement

[2019 JSConf Korea](https://2019.jsconfkorea.com/en/) will be held in Sep. 2019

Participating as a speaker, I want to introduce **nact** as an akka-like actor system in JavaScript.

The videos of the announcement will be shared on the [JSConf YouTube channel](https://www.youtube.com/channel/UCzoVCacndDCfGDf41P-z0iA) after the conference ends.

I hope it will be a good chance for nact to get popular worldwide.

I'm busy that the deadline for the proposal is near.

Sooner or later, **nact** would have to be prepared to welcome new contributors and those who are interested in.

**Comment by ncthbrt** [comment]
@civilizeddev Just an update. Merged your `ts-nact` fork into nact's dev branch. Haven't had much time to work on it yet, and still learning typescript. However at a surface level, I feel we can do better with the typing of actor refs.

**Comment by ncthbrt** [comment]
I'm closing this issue for now as I've started opening up more specific typescript issues.
