### ISSUE TITLE
AbstractPersistenceEngine.events(): Result

### ISSUE THREAD

**Issue by civilizeddev** [ncthbrt/nact#56]
## Current

- **AbstractPersistenceEngine.events()** in [here](https://github.com/ncthbrt/nact/blob/master/lib/persistence/persistent-actor.js#L91) returns **Result** that has **reduce()** function.
- But **Result** is only defined in [here](https://github.com/ncthbrt/nact-persistence-postgres/blob/master/lib/index.js#L6), not in **nact/lib/persistence**.

## Problem

- I'd had to define another **Result** for **nact-persistence-mysql**

Given,

```
class Result<T> {
  constructor (promise: Promise<T>) {
    this.promise = promise;
  }

  public then(...args) {
    return this.promise.then(...args);
  }

  public reduce(...args) {
    return this.promise.then(result => result.reduce(...args));
  }
}
```

Q. What type of parameters and return of the functions: `then()`, `reduce()`  should be?

**Comment by ncthbrt** [comment]
Result was just a helper to be able to call reduce on the inner values of a
promise. The reason I didn't put it in the main repo was in case other
databases supported streaming of values.

**Comment by ncthbrt** [comment]
Would probably be best to just define an interface, perhaps something like this:
```typescript
interface PersistentEngineResult<T> {
  then<U>(handler: ((value: T) => (U | Promise<U>))): Promise<U>;
  reduce<U>(reducer: ((state: U, value: T, index: number) => U), initialState : (U)): Promise<U>;
}
```
