### ISSUE TITLE
Typescript ActorRefs are unsoundly typed. 

### ISSUE THREAD

**Issue by ncthbrt** [ncthbrt/nact#57]
I've started a branch `/refactor-typescript` to address these issues.

Problems present on current dev branch are as follows: 
1. Sender - The `sender` property  makes sound typing impossible as it either couples  the senders and recipients too tightly together or it removes the type information. Sender is to be removed in a soundly typed implemention. c.f. reason-nact
2. Children - The Children Ref of a given actor are currently typed `ActorRef<any>` they should be instead changed to `ActorRef<unknown>` to indicate that by default we do not know what messages a child can handle in advance. In general any any should be removed from the public facing api. 
3. Context, SupervisionContext, Actor all need to include the message type of the parent as well as the current actor. This *IS* known by a child actor in advance and allows a child actor to freely message a parent without casting.  
4. Serialized messages and decoders/encoders - Messages coming back from the database cannot be soundly typed as this is out of nact's control. Persistent actors should be typed as `Json` by default unless they include a encoder/decoder tuple which maps Json to an actual type. 

Unrelated to soundness, but still important: 
1. References - Currently references include `get` methods and extraneous fields.  These fields and methods need to be removed as references must be serializable to json without information loss. 
2. Separation of implementation details from public API - Nact is kind of like an iceburg. There is a lot of implementation details that users don't need to directly interact with unless they wish to extend the framework. It would be nice to make it clearer in source which files are part of the public API and which are not. Currently I removed implementation details to a folder called `internals` (for want of a better name)

**Comment by ncthbrt** [comment]
Tagging @civilizeddev on this.

**Comment by civilizeddev** [comment]
# 번역

아래 문제를 해결하기 위해 `/refactor-typescript` 브랜치를 시작했습니다.

현재 `/dev` 브랜치의 문제는 다음과 같습니다.

## 1. Sender

```
interface Context {
  ...
  sender: ActorRef<any>
}
```

- https://github.com/ncthbrt/nact/blob/dev/nact-core/src/actor/Context.ts#L11

- Context의 sender 프로퍼티에 적절한 타입을 특정하는 것이 불가합니다.:
  - sender의 액터 참조 타입을 특정하면, 송신자, 수신자 액터를 서로 강하게 결합시키게 됩니다.
  - 만약 액터 타입을 `any`로 두면, 타입 정보가 무력해집니다.
- 그래서 `sender` 프로퍼티는 타입이 있는 구현에서는 제거되어야 합니다. *c.f. reason-nact*
  - https://github.com/ncthbrt/reason-nact/blob/master/src/Nact.re#L89

> While using TypeScript, I don't think it's our goal to implement kind of `akka-actor-typed` (or even reason-nact). My intention was to keep current implementation and just to provide type definitions for TypeScript. There are many of projects doing this way. Users could bear with `any` type in some points. I don't want breaking changes at this moment.
>
> ## References
> - https://doc.akka.io/docs/akka/2.5/typed/coexisting.html
> - https://doc.akka.io/docs/akka/2.5/typed/actors.html#relation-to-akka-untyped-actors
>


## 2. Children

> The Children Ref of a given actor are currently typed ActorRef<any> they should be instead changed to ActorRef<unknown> to indicate that by default we do not know what messages a child can handle in advance.
- You're right. `any` and `unknown` are slightly different, but they are exchangeable.
- We can adopt `interface UntypedActorRef` instead of `ActorRef<T>` for this.

> In general any any should be removed from the public facing api.
- You're right.
- While using TypeScript, there would be the cases that `any` be used inevitably. It's good to compromise in cases.


## 3. Context

Compared to `akka`, `nact` is `akka-actor`(untyped), and `reason-nact` is `akka-actor-typed`. As I said before, I think it's difficult to jump into fully soundly typed at once.

Q. Do you want the next nact release to be kind of `reason-nact`, which is fully typed one?


## 4. JSON

- There is no type like `JSON`
- It should be `any`
- Cases
  - `JSON.parse` takes `string`
  - [typescript-json-serializer](https://github.com/GillianPerard/typescript-json-serializer) takes `any` (assuming that it is well-formed JavaScript Object)

**Comment by civilizeddev** [comment]
> Unrelated to soundness, but still important:

> References - Currently references include get methods and extraneous fields. These fields and methods need to be removed as references must be serializable to json without information loss.

- References are instantiated from class: `ActorReference`, `ActorSystemReference`
- Those instances have prototype chain to its class. `[Function ActorReference]`
- While JSON.parse returns only plain object `[Function Object]`, it's possible to restore its prototype by using [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create) or [typescript-json-serializer](https://github.com/GillianPerard/typescript-json-serializer)
- Wouldn't make sense that instance of class should be restored as the same as the original?

> Separation of implementation details from public API - Nact is kind of like an iceburg. There is a lot of implementation details that users don't need to directly interact with unless they wish to extend the framework. It would be nice to make it clearer in source which files are part of the public API and which are not. Currently I removed implementation details to a folder called internals (for want of a better name)

- While I'm currently engaged in JavaScript, I am familiar with Java/Scala.
- That **nact** is inspired by akka, what if `nact` has the same interface as `akka`?

**Comment by ncthbrt** [comment]
> While JSON.parse returns only plain object [Function Object], it's possible to restore its prototype by using Object.create or typescript-json-serializer

The problem is that users may pass around references in arbitrarily defined messages. Which means that we can't reliably inject a constructor in JSON.parse. 

In terms of soundness, my original thought was to maintain compatibility, but after thinking a lot more deeply I think it would be a mistake to introduce an unsound then sound API later. I'd like there to be only one canonical API, as that is one of the design principles for this library; sane defaults, less configuration. Means you aren't splitting users and giving them uncessary choices. I am confident we can get this right off the bat because of the reason wrapper around Nact which had to deal with the same challenges. I am also fairly confident that the public API won't change too drastically with the exception of eliminating sender.

Relatedly (and having a lot of Akka xp) I don't want to copy Akka's API as I consider it to be a slightly weak design (but a good technical achievement). It is too big, with too many options, and at least from what I've seen in the dotnet port, wouldn't be idiomatic js.

**Comment by civilizeddev** [comment]
## Q. What would it look like if `sender` get removed from Context?

- https://github.com/ncthbrt/reason-nact/blob/master/src/Nact.re#L88
- https://github.com/ncthbrt/reason-nact/blob/master/src/Nact.re#L100

I'm not familiar with ReasonML. Can you explain me what the alternative would be?

## References

- [Akka Typed](https://doc.akka.io/docs/akka/current/typed/cluster.html)

**Comment by ncthbrt** [comment]
When sender is removed from the context, users would then be required to include `ActorReferences<T>` in their message models. The consequence of this is that `query()` has to take in a factory function which accepts a temporary reference as an argument and returns a concrete message as a result. 

An example
The old way of doing a query:
`var result = await query(new GetCarriageInformation(carriageId), 1000*seconds);`

The new way (which is actually also currently supported):
`var result = await query((sender) => new GetCarriageInformation(carriageId, sender), 1000*seconds);`

**Comment by civilizeddev** [comment]
It looks the same as the way akka-typed adopt.

But I couldn't find the implementation of `query` you mentioned as the new way from here:
https://github.com/ncthbrt/nact/blob/master/lib/functions.js#L10

Is it a trick in JS that I don't know?

**Comment by ncthbrt** [comment]
The implementation of query is inside the query method in the actor class

**Comment by civilizeddev** [comment]
Then It would look like this:

## Public API: query

```
function query<T, U>(
  actorRef: ActorRef<T>,
  msg: (ref: ActorRef<U>) => T,
  timeout: Timeout
): Promise<U>
```

## References

- [akka-actor-typed/AskPattern](https://github.com/akka/akka/blob/master/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala#L62)

**Comment by ncthbrt** [comment]
Yes. However this should probably change to:  `msg: (ref:
TemporaryReference<U>) => T`

**Comment by civilizeddev** [comment]
But replying actors don't care what type of implementation of ActorRef is, because they just call `dispatch<R>(replyTo: ActorRef<R>, msg: R)`

I think `msg: (ref: ActorRef<U>) => T` still makes sense, isn't it?

**Comment by ncthbrt** [comment]
Well if we go by: https://github.com/ncthbrt/nact/blob/refactor-typescript/nact-core/src/References.ts,
It could also just be `Reference<T>` which means it could be any type of reference.

**Comment by ncthbrt** [comment]
@civilizeddev  I've updated this branch: https://github.com/ncthbrt/nact/tree/refactor-typescript 
I'm a lot happier with the direction the core module is going in after I refactored some of your code to add additional soundness.

**Comment by civilizeddev** [comment]
@ncthbrt 

As far as I know there is no kind of notion of JSON in TypeScript.
But **JSON** itself is **J**ava**S**cript **O**bject **N**otation, isn't it?
Messages can be primitives or object. So it is likely to be `any`.

`type JSON = any`

## Not Concerned

- Event => PersistedEvent
  - [PersistentActor.persist](https://github.com/ncthbrt/nact/blob/master/lib/persistence/persistent-actor.js#L133)
- PersistedEvent => DB Row
  - [PersistentEngine.persist](https://github.com/ncthbrt/nact-persistence-postgres/blob/master/lib/index.js#L71)
- DB Row => PersistedEvent
  - [PersistentEngine.mapDbModelToDomainModel](https://github.com/ncthbrt/nact-persistence-postgres/blob/master/lib/index.js#L31)
- StateSnapshot => PersistedSnapshot
  - [PersistentActor.afterMessage](https://github.com/ncthbrt/nact/blob/master/lib/persistence/persistent-actor.js#L43)
- PersistedSnapshot => DB Row
  - [PersistentEngine.takeSnapshot](https://github.com/ncthbrt/nact-persistence-postgres/blob/master/lib/index.js#L106)
- DB Row => PersistedSnapshot
  - [PersistentEngine.mapDbModelToSnapshotDomainModel](https://github.com/ncthbrt/nact-persistence-postgres/blob/master/lib/index.js#L42)

## Concerned 

- PersistedEvent => Event / JSON => Event
  - [PersistentActor.decoder](https://github.com/ncthbrt/nact/blob/master/lib/persistence/persistent-actor.js#L97)
- PersistedSnapshot => StateSnapshot / JSON => StateSnapshot
  - [PersistentActor.snapshotDecoder](https://github.com/ncthbrt/nact/blob/master/lib/persistence/persistent-actor.js#L85)
- StateSnapshot => JSON
  - snapshotEncoder
- Event => JSON
  - encoder

## Q. What are you concerned in detail?

**Comment by ncthbrt** [comment]
I created less invasive typescript bindings. These should quite accurately and soundly type the actors in the library
