### ISSUE TITLE
multicore cup

### ISSUE THREAD

**Issue by yunmin97** [ncthbrt/nact#74]
Is nact ability to take full advantage of multicore cup resources ?
or all atcors run only on a single cup?

**Comment by ncthbrt** [comment]
Each actor system runs on a single core. You could use node's multi
processing features to create more than one system, and then create actors
which would bridge the different systems.

We've taken a similar approach to allow for communication between different
services in our kubernetes cluster.

**Comment by yunmin97** [comment]
sorry I'm not sure..

1. How do actors on system A communicate with actors on system B?  
2. dispatch(A-actor, 'communicate between A&B system', B-actor);  does this work?
or i must use process.send({ msg: 'word to A-system' }) to deal with the communication between two processes(systems)?
