### ISSUE TITLE
dispatch has wrong type signature

### ISSUE THREAD

**Issue by allain** [ncthbrt/nact#83]
dispatch has type signature  `function dispatch<T>(actor: Ref<T>, msg: T): void;` but the example at https://nact.io/en_uk/lesson/javascript/actor-communication demonstrates passing it a 3rd argument.

## Expected Behavior
It should document itself correctly.

## Current Behavior
It is missing documentation about the third param.

## Steps to Reproduce (for bugs)
1. Follow the getting started guide
2. When you get to the Communication step in vscode have a look at the tooltip it shows for dispatch.

## Context
It's not a great experience to have the docs at your fingertips be incorrect.

## Your Environment
* Version used: ^7.3.0
* Environment: vscode 1.46.0

**Comment by ncthbrt** [comment]
Hi Allain. Thanks for opening this issue.

I need to update that and other examples. The third param has been retained
for backwards compatibility but deliberately excluded from the typescript
types.

The third param allowed a developer to specify the sender, which would be
included in the context object.

When adding typings, first in ReasonML, and then in typescript, it became
clear that this sender argument is an antipattern and that even in an
untyped languages like js, it's better to include the sender as a
deliberate part of the message protocol. It makes things much more
explicit, and allows the typing of state machine like semantics.

I didn't want to break users however who were relying on the sender param,
so I merely hid it in the types.

**Comment by allain** [comment]
Makes sense. I suppose the issue should be changed to request an improvement to the example so that it's not an anti-pattern?
