### ISSUE TITLE
when trying to compile typescript file with nact, I receive error saying dispatch accepts only 2 arguments

### ISSUE THREAD

**Issue by zebralight** [ncthbrt/nact#86]
## Expected Behavior
When compiling a typescript file that calls `dispatch` from nact with 3 arguments, I should not receive this error:
```
actor.ts:39:34 - error TS2554: Expected 2 arguments, but got 3.
39   dispatch(ctx.sender, ctx.name, ctx.self);
```

## Current Behavior
I receive the error when compiling:
```
actor.ts:39:34 - error TS2554: Expected 2 arguments, but got 3.
39   dispatch(ctx.sender, ctx.name, ctx.self);
```

## Possible Solution
Update typing to allow for a 3rd optional argument

## Steps to Reproduce (for bugs)
1. Add the code from ping pong tutorial:
```
import {start,dispatch, spawnStateless} from 'nact';
const delay = (time) => new Promise((res) => setTimeout(res, time));

const ping = spawnStateless(system, async (msg, ctx) =>  {
  console.log(msg);
  // ping: Pong is a little slow. So I'm giving myself a little handicap :P
  await delay(500);
  dispatch(ctx.sender, ctx.name, ctx.self);
}, 'ping');

const pong = spawnStateless(system, (msg, ctx) =>  {
  console.log(msg);
  dispatch(ctx.sender, ctx.name, ctx.self);  
}, 'pong');

dispatch(ping, 'begin', pong);
```
2. Compile with `tsc`

## Context
I'm trying to use nact with typescript

## Your Environment

* Version used: nact 7.3.1
* Environment name and version (e.g. Node v8.8) node 14.3.0
* Operating System and version: macos catalina

**Comment by ncthbrt** [comment]
I've updated the docs @zebralight to reflect the new signatures
